import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime
from dateutil.relativedelta import relativedelta

########################
##########TODO##########
########################
"""
-indexing across years and months
-indexing across dates for given regions or across entire states or cities
-calculation of finding the percent change over a given period
"""

def date_ranger(t_begin, t_end, index_by="year"):
    """
    t_begin: list of integers
    t_end: list of integers, should proceed t_begin
    period: integer representing how long should be searched
    """
    #var declaration
    date_array = []
    i = 0
    t_current = datetime.date(t_begin[0], t_begin[1], t_begin[2])
    t_stop = datetime.date(t_end[0], t_end[1], t_end[2])
    print(t_current)

    #array generated by years
    if index_by == "year":
        delta = relativedelta(years=1)
        while t_current < t_stop:
            date_array.append(str(t_current))
            t_current = t_current + delta
    
    elif index_by == "month":
        d_month = relativedelta(months=1)
        d_days = datetime.timedelta(days=1)
        while t_current < t_stop:
            date_array.append(str(t_current))
            t_current = t_current + d_month

            current_month = t_current.month
            next_month = current_month
            while next_month == current_month:
                t_current = t_current + d_days 
                next_month = t_current.month
            
            t_current = t_current - d_days
            

    else:
        print("Error: Non-indexible type")
        return

    return date_array


#get datafile and define vars
input_csv = "neighborhood.csv"

df = pd.read_csv(input_csv)
#timeframe = ['RegionName', 'StateName', dates]

#print(df.columns[:])
#print(df.loc[:, timeframe])

t_begin = [2019, 12, 31]
t_end = [2025, 12, 31]
print(date_ranger(t_begin, t_end, "month"))